version: '3'

services:
  synapse:
    container_name: hermes-synapse
    image: docker.io/matrixdotorg/synapse:latest
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/conf
    volumes:
      - ./data-syn:/data
      - ./files:/conf
    depends_on:
      - db
    ports:
      - 8448:8448/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-synapse.entryPoints=http
      - traefik.http.routers.http-synapse.rule=Host(`${HERMES_HOSTNAME}`)
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-synapse.middlewares=https_redirect
      - traefik.http.routers.https-synapse.entryPoints=https
      - traefik.http.routers.https-synapse.rule=Host(`${HERMES_HOSTNAME}`)
      - traefik.http.routers.https-synapse.service=synapse
      - traefik.http.routers.https-synapse.tls=true
      - traefik.http.services.synapse.loadbalancer.server.port=8008
      - traefik.http.routers.https-synapse.tls.certResolver=le-ssl
    networks:
      default:
        ipv4_address: 10.10.10.4

  db:
    container_name: hermes-db
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_USER=${HERMES_DB_USER}
      - POSTGRES_PASSWORD=${HERMES_DB_PASS}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data:/var/lib/postgresql/data:default
    networks:
        default:
          ipv4_address: 10.10.10.2

  element:
    container_name: hermes-element
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./element-config.json:/app/config.json
    networks:
      default:
        ipv4_address: 10.10.10.3

networks:
  default:
    external:
      name: matrix_network