location = / {
  return 302 https://www.dreampip.com$request_uri;
}

# this actually belongs here
location /nextcloud/ {
        auth_basic off;
        sub_filter "/core/" "/nextcloud/core/";
        sub_filter_once off;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Host $host;
        rewrite ^/nextcloud(.*)$ $1 break;
        proxy_pass http://nextcloud/;
        client_max_body_size 512M;
}

# location /nextcloud/.well-known/carddav {
#     return 301 $scheme://$host/remote.php/dav;
# }

# location /nextcloud/.well-known/caldav {
#     return 301 $scheme://$host/remote.php/dav;
# }

#location ^~ /.well-known {
#    return 301 $scheme://$host/index.php$uri;
#}

location ~ ^(/_matrix|/_synapse/client|/_synapse/admin|/.well-known) {
        note: do not add a path (even a single /) after the port in `proxy_pass`,
        otherwise nginx will canonicalise the URI and cause signature verification
        errors.
       proxy_pass http://hermes-synapse:8008;
       proxy_set_header X-Forwarded-For $remote_addr;
       proxy_set_header X-Forwarded-Proto $scheme;
       proxy_set_header Host $host;

        Nginx by default only allows file uploads up to 1M in size
        Increase client_max_body_size to match max_upload_size defined in homeserver.yaml
       client_max_body_size 50M;

        Synapse responses may be chunked, which is an HTTP/1.1 feature.
      proxy_http_version 1.1;
}

# collabora settings
 location ^~ /browser {
   proxy_pass http://collabora:9980;
   proxy_set_header Host $host;
 }

 # WOPI discovery URL
 location ^~ /hosting/discovery {
   proxy_pass http://collabora:9980;
   proxy_set_header Host $host;
 }


 # Capabilities
 location ^~ /hosting/capabilities {
   proxy_pass http://collabora:9980;
   proxy_set_header Host $host;
 }


 # main websocket
 location ~ ^/cool/(.*)/ws$ {
   proxy_pass http://collabora:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $host;
   proxy_read_timeout 36000s;
 }


 # download, presentation and image upload
 location ~ ^/(c|l)ool {
   proxy_pass http://collabora:9980;
   proxy_set_header Host $host;
 }


 # Admin Console websocket
 location ^~ /cool/adminws {
   proxy_pass http://collabora:9980;
   proxy_set_header Upgrade $http_upgrade;
   proxy_set_header Connection "Upgrade";
   proxy_set_header Host $host;
   proxy_read_timeout 36000s;
 }