services:
  hermes-model-redis:
    image: redis:alpine
    container_name: hermes-model-redis
    restart: always
    networks:
      - hermes-net-model-cloud
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - "${HERMES_PORT_PREFIX}16:6379/tcp"

  hermes-model-mariadb:
    image: mariadb
    container_name: hermes-model-mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      hermes-net-model-cloud:
        ipv4_address: ${HERMES_MODEL_CLOUD_MARIA_IP}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${HERMES_CLOUD_DB_PASS}
      - MYSQL_DATABASE=${HERMES_CLOUD_DB_NAME}
      - MYSQL_USER=${HERMES_CLOUD_DB_USER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - "${HERMES_PORT_PREFIX}17:3306/tcp"

  # hermes-model-postgres:
  #   image: docker.io/postgres:12-alpine
  #   container_name: hermes-model-postgres
  #   networks:
  #     hermes-net-model-chat:
  #       ipv4_address: ${HERMES_MODEL_CHAT_DB_FIXED_IP}
  #   environment:
  #     - POSTGRES_USER=${HERMES_CHAT_DB_USER}
  #     - POSTGRES_PASSWORD=${HERMES_CHAT_DB_PASS}
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data:default
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    # ports:
    #   - "${HERMES_PORT_PREFIX}18:5432/tcp"


networks:
  hermes-net-weagle:
    name: hermes-net-weagle
    driver: bridge
    external: true
  hermes-net-model-all:
    name: hermes-net-model-all
    driver: bridge
    external: true
  hermes-net-model-chat:
    name: hermes-net-model-chat
    driver: bridge
    external: true
  hermes-net-model-cloud:
    name: hermes-net-model-cloud
    driver: bridge
    external: true
  # radio:
  #   name: hermes_auth_radio
  #   driver: bridge
  #   external: true