services:
  redis:
    image: redis:alpine
    container_name: hermes_model_redis
    restart: always
    networks:
      - hermes_net_model_cloud
    logging:
      options:
        max-size: "10m"
        max-file: "3"

  mariadb:
    image: mariadb
    container_name: hermes_model_mariadb
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    networks: 
      - hermes_net_model_cloud
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    volumes:
      - ./data/mariadb:/var/lib/mysql
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=UTC
      - MYSQL_RANDOM_ROOT_PASSWORD=true
      - MYSQL_PASSWORD=${HERMES_CLOUD_DB_PASS}
      - MYSQL_DATABASE=${HERMES_CLOUD_DB_NAME}
      - MYSQL_USER=${HERMES_CLOUD_DB_NAME}

  # postgres:
  #   container_name: hermes_model_postgres
  #   image: docker.io/postgres:12-alpine
  #   environment:
  #     - POSTGRES_USER=${HERMES_DB_USER}
  #     - POSTGRES_PASSWORD=${HERMES_DB_PASS}
  #     - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
  #   volumes:
  #     - ./data/postgres:/var/lib/postgresql/data:default
  #   networks:
  #       hermes_net_modle_chat:
  #         ipv4_address: 101.203.3.2


networks:
  hermes_net_weagle:
    name: hermes_net_weagle
    driver: bridge
    external: true
  hermes_net_model_all:
    name: hermes_net_model_all
    driver: bridge
    external: true
  hermes_net_model_chat:
    name: hermes_net_model_chat
    driver: bridge
    external: true
  hermes_net_model_cloud:
    name: hermes_net_model_cloud
    driver: bridge
    external: true
  # radio:
  #   name: hermes_auth_radio
  #   driver: bridge
  #   external: true