services:
  hermes-auth-ldap:
    image: bitnami/openldap:latest
    container_name: hermes-auth-ldap
    environment:
      - LDAP_ADMIN_USERNAME=${HERMES_LDAP_ADMIN_USER}
      - LDAP_ADMIN_PASSWORD=${HERMES_LDAP_ADMIN_PASS}
      - LDAP_USERS=${HERMES_FIRST_USER}
      - LDAP_PASSWORDS=${HERMES_FIRST_USER_PASS}
    networks:
      - hermes-net-weagle
    volumes:
      - './data/openldap:/bitnami/openldap'
      # - './data/openldap_data:/bitnami/openldap/data'
    dns:
      - ${HERMES_DNS_RESOLVER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - "${HERMES_PORT_PREFIX}01:1389/tcp"
      - "${HERMES_PORT_PREFIX}02:1689/tcp"

networks:
  hermes-net-weagle:
    name: hermes-net-weagle
    driver: bridge
    external: true
