version: '3'

services:
  synapse:
    container_name: hermes_synapse
    build: .
    restart: unless-stopped
    environment:
      - SYNAPSE_CONFIG_PATH=/data/homeserver.yaml
      - PYTHONPATH="$${PYTHONPATH}:/var/task"
    volumes:
      - ./files:/data:default
    depends_on:
      - db
    ports:
      - ${HERMES_MATRIX_INTERNAL_PORT}:8448/tcp
    labels:
      - traefik.enable=true
      - traefik.http.routers.http-synapse.entryPoints=http
      - traefik.http.routers.http-synapse.rule=Host(`${HERMES_HOSTNAME}`)
      - traefik.http.middlewares.https_redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.https_redirect.redirectscheme.permanent=true
      - traefik.http.routers.http-synapse.middlewares=https_redirect
      - traefik.http.routers.https-synapse.entryPoints=https
      - traefik.http.routers.https-synapse.rule=Host(`${HERMES_HOSTNAME}`)
      - traefik.http.routers.https-synapse.service=synapse
      - traefik.http.routers.https-synapse.tls=true
      - traefik.http.services.synapse.loadbalancer.server.port=8008
      - traefik.http.routers.https-synapse.tls.certResolver=le-ssl
    networks:
      default:
        ipv4_address: 10.10.10.4

  # move to data layer
  postgres:
    container_name: hermes_postgres
    image: docker.io/postgres:12-alpine
    environment:
      - POSTGRES_USER=${HERMES_DB_USER}
      - POSTGRES_PASSWORD=${HERMES_DB_PASS}
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./data:/var/lib/postgresql/data:default
    networks:
        default:
          ipv4_address: 10.10.10.2

  # move to web clients
  element:
    container_name: hermes_element
    image: vectorim/element-web:latest
    restart: unless-stopped
    volumes:
      - ./element-config.json:/app/config.json
    networks:
      default:
        ipv4_address: 10.10.10.3

  # bridge-whatsapp:
  #   container_name: hermes_whatsapp
  #   image: dock.mau.dev/mautrix/whatsapp:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/whatsapp:/data

  # bridge-telegram:
  #   container_name: hermes_telegram
  #   image: dock.mau.dev/mautrix/telegram:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/telegram:/data

  # bridge-signal:
  #   container_name: hermes_signal
  #   image: dock.mau.dev/mautrix/signal:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/signal:/data

  # bridge-slack:
  #   container_name: hermes_slack
  #   image: dock.mau.dev/mautrix/slack:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/slack:/data

  # bridge-meta-messenger:
  #   container_name: hermes_meta-messenger
  #   image: dock.mau.dev/mautrix/meta:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/meta/messenger:/data

  # bridge-meta-instagram:
  #   container_name: hermes_meta-instagram
  #   image: dock.mau.dev/mautrix/meta:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/meta/instagram:/data

  # bridge-discord:
  #   container_name: hermes_discord
  #   image: dock.mau.dev/mautrix/discord:latest
  #   restart: unless-stopped
  #   volumes:
  #     - ./data/bridge/discord:/data

networks:
  default:
    external:
      name: hermes_chat