# hermes/ingress/manualtls/cluster(prod)
services:
  hermes_ingress_weagle:
    image: docker.io/traefik:latest
    container_name: hermes_ingress_traefik
    restart: always
    ports:
      # - "80:80"
      # - "443:443"
      # - "8080:8080"
      - target: 80
        published: 80
        mode: host
      - target: 443
        published: 443
        mode: host
      - target: 8080
        published: 8080
        mode: host
    networks:
      hermes_net_weagle:
          ipv4_address: ${HERMES_DNS_RESOLVER}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--providers.docker"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic.yml:/etc/traefik/dynamic.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes:
      - "../certs/data:/certs/"
      - "./data/traefik/acme.json:/acme.json"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  hermes_ingress_whoami:
    image: traefik/whoami
    container_name: hermes_ingress_whoami
    restart: always
    environment:
      - WHOAMI_PORT_NUMBER: 1234
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - ${HERMES_PORT_PREFIX}99:1234/tcp

  hermes_ingress_grafana:
    image: grafana/grafana-oss
    container_name: hermes_ingress_grafana
    restart: always
    networks:
      - hermes_net_weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${HERMES_GRAFANA_SECURITY_ADMIN_PASS}
      GF_SERVER_DOMAIN: ${HERMES_HOSTNAME}
      GF_SERVER_ROOT_URL: https://${HERMES_HOSTNAME}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/_sre/graf`)"
      - "traefik.http.routers.grafana.tls=${HERMES_TLS}"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - ${HERMES_PORT_PREFIX}08:3000/tcp

  hermes_ingress_prometheus:
    image: prom/prometheus
    container_name: hermes_ingress_prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - ${HERMES_PROM_VOLUME}:/etc/prometheus/prometheus
    networks:
      - hermes_net_weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=768MB"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/_sre/prom`)"
      - "traefik.http.routers.prometheus.tls=${HERMES_TLS}"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - ${HERMES_PORT_PREFIX}09:9090/tcp

  node-exporter:
    image: prom/node-exporter
    container_name: hermes_ingress_node-exporter
    restart: always
    networks:
      - hermes_net_weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeexporter.rule=PathPrefix(`/_sre/prom/node`)"
      - "traefik.http.routers.nodeexporter.tls=${HERMES_TLS}"
      - "traefik.http.services.nodeexporter.loadbalancer.server.port=9100"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - ${HERMES_PORT_PREFIX}10:9100/tcp
  
  alert-manager:
    image: prom/alertmanager
    container_name: hermes_ingress_alert-manager
    restart: always
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - hermes_net_weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=PathPrefix(`/_sre/prom/alerts`)"
      - "traefik.http.routers.alertmanager.tls=${HERMES_TLS}"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}
    # traefik ignores ports,
    # keep it for k8s/helm charts only. 
    ports:
      - ${HERMES_PORT_PREFIX}11:9093/tcp

networks:
  hermes_net_weagle:
    name: hermes_net_weagle
    driver: bridge
    external: true
  hermes_net_chat:
    name: hermes_net_chat
    driver: bridge
    external: true
  hermes_net_cloud:
    name: hermes_net_cloud
    driver: bridge
    external: true
  # radio:
  #   name: hermes_net_radio
  #   driver: bridge
  #   external: true