# hermes/ingress/manualtls/cluster(prod)
services:
  weagle:
    image: docker.io/traefik:latest #v2.5
    container_name: hermes-traefik
    restart: always
    ports:
      - target: 80
        published: 180
        mode: host
      - target: 443
        published: 1443
        mode: host
      - target: 8080
        published: 1808
        mode: host
    networks:
      weagle:
          ipv4_address: ${HERMES_DNS_RESOLVER}
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--providers.docker"
      - "--providers.docker.exposedbydefault=false"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./dynamic.yml:/etc/traefik/dynamic.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    volumes:
      - "../certs/data:/certs/"
      - "./data/traefik/acme.json:/acme.json"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: traefik/whoami
    container_name: hermes-whoami
    restart: always

  grafana:
    image: grafana/grafana-oss
    container_name: hermes-grafana
    restart: always
    networks:
      - hermes-weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${HERMES_GRAFANA_SECURITY_ADMIN_PASS}
      GF_SERVER_DOMAIN: ${HERMES_HOSTNAME}
      GF_SERVER_ROOT_URL: https://${HERMES_HOSTNAME}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: 'true'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana.rule=PathPrefix(`/_sre/graf`)"
      - "traefik.http.routers.grafana.tls=${HERMES_TLS}"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}

  prometheus:
    image: prom/prometheus
    container_name: hermes-prometheus
    restart: always
    volumes:
      - "./prometheus.yml:/etc/prometheus/prometheus.yml"
      - ${HERMES_PROM_VOLUME}:/etc/prometheus/prometheus
    networks:
      - hermes-weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--storage.tsdb.retention.size=768MB"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus.rule=PathPrefix(`/_sre/prom`)"
      - "traefik.http.routers.prometheus.tls=${HERMES_TLS}"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}

  node-exporter:
    image: prom/node-exporter
    container_name: hermes-node-exporter
    restart: always
    networks:
      - hermes-weagle
        logging:
    options:
      max-size: "10m"
      max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nodeexporter.rule=PathPrefix(`/_sre/prom/node`)"
      - "traefik.http.routers.nodeexporter.tls=${HERMES_TLS}"
      - "traefik.http.services.nodeexporter.loadbalancer.server.port=9100"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}
  
  alert-manager:
    image: prom/alertmanager
    container_name: hermes-alert-manager
    restart: always
    volumes:
      - "./alertmanager.yml:/alertmanager/alertmanager.yml"
    networks:
      - hermes-weagle
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.alertmanager.rule=PathPrefix(`/_sre/prom/alerts`)"
      - "traefik.http.routers.alertmanager.tls=${HERMES_TLS}"
      - "traefik.http.services.alertmanager.loadbalancer.server.port=9093"
      - "traefik.docker.network=weagle"
    dns:
      - ${HERMES_DNS_RESOLVER}

networks:
  weagle:
    name: hermes-weagle
    driver: bridge
    external: true
  matrix:
    name: hermes-chat
    driver: bridge
    external: true
  cloud:
    name: hermes-cloud
    driver: bridge
    external: true
  # radio:
  #   name: hermes-radio
  #   driver: bridge
  #   external: true