# hermes/ingress/traefik/static
global:
  checkNewVersion: true

log:
  level: DEBUG

api:
  insecure: false
  dashboard: true

ping: {}

metrics:
  prometheus:
    buckets: 0.1,0.3,1.2,5.0

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    fileName: /etc/traefik/dynamic.yml
    watch: true