# hermes/ingress/traefik/static
global:
  checkNewVersion: true

tls:
  # options:
  #   default:
  #     sniStrict: true
  stores:
    default:
      defaultCertificate:
        certFile: /etc/certs/${HERMES_CERT_FILE}
        keyFile: /etc/certs/${HERMES_CERT_KEY_FILE}
  domains:
    main: ${HERMES_HOSTNAME}
  certificates:
    - certFile: /etc/certs/${HERMES_CERT_FILE}
      keyFile: /etc/certs/${HERMES_CERT_KEY_FILE}
      stores:
        - default

log:
  level: DEBUG

accesslog: true

api:
  insecure: false
  dashboard: true

ping: {}

metrics:
  prometheus:
    buckets: 0.1,0.3,1.2,5.0

providers:
  docker:
    network: hermes-net-weagle
    exposedByDefault: false
    watch: true
  # file:
  #   fileName: /etc/traefik/dynamic.yml
  #   watch: true

certificateResolvers:
  le-ssl:
    acme:
      email: ${HERMES_ROOT_HANDLE}@${HERMES_MAIL_MAIN_HOSTNAME}
      storage: /etc/certs/acme.json
      httpchallenge:
        entryPoint:
          - web

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    asDefault: true
    address: :443
  smtp:
    address: :25
  submissions:
    address: :587
  imap:
    address: :143
  imaps:
    address: :993
  pop3:
    address: :110
  pop3s:
    address: :995
  sieve:
    address: :4190