# hermes/ingress/traefik/static
global:
  checkNewVersion: true

log:
  level: DEBUG

accesslog: true

api:
  insecure: false
  dashboard: true

ping: {}

metrics:
  prometheus:
    buckets: 0.1,0.3,1.2,5.0

providers:
  docker:
    network: hermes-net-weagle
    exposedByDefault: false
    watch: true
  # file:
  #   fileName: /etc/traefik/dynamic.yml
  #   watch: true

certificateResolvers:
  le-ssl:
    acme:
      dnsChallenge:
        provider: cloudflare
        resolvers: 1.1.1.1:53,1.0.0.1:53
        delayBeforeCheck: 90
      email: ${HERMES_ROOT_HANDLE}@${HERMES_MAIL_MAIN_HOSTNAME}
      storage: "/etc/traefik/acme/acme.json"
      # httpChallenge:
      #   entryPoint:
      #     - web
      # tlsChallenge: {}
# - --certificatesResolvers.dns-cloudflare.acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory #LetsEncrypt Staging Server (uncomment when testing)
# - --certificatesResolvers.dns-cloudflare.acme.email=$EMAIL
# - --certificatesResolvers.dns-cloudflare.acme.storage=/acme.json
# - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.provider=cloudflare
# - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.resolvers=1.1.1.1:53,1.0.0.1:53
# - --certificatesResolvers.dns-cloudflare.acme.dnsChallenge.delayBeforeCheck=90

#  ### HTTP Routers
# - "traefik.http.routers.traefik-rtr.entrypoints=https"
# - "traefik.http.routers.traefik-rtr.rule=Host(`traefik.$DOMAINNAME`)"
# - "traefik.http.routers.traefik-rtr.tls=true"
# - "traefik.http.routers.traefik-rtr.tls.certResolver=dns-cloudflare" #Comment out this line after first run of Traefik to force the use of wildcard certs
# - "traefik.http.routers.traefik-rtr.tls.domains[0].main=$DOMAINNAME"
# - "traefik.http.routers.traefik-rtr.tls.domains[0].sans=*.$DOMAINNAME"

entryPoints:
  web:
    address: :80
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    asDefault: true
    address: :443
  smtp:
    address: :25
  submissions:
    address: :587
  imap:
    address: :143
  imaps:
    address: :993
  pop3:
    address: :110
  pop3s:
    address: :995
  sieve:
    address: :4190