# Fail2Ban configuration file
# hermes_cloud:drive(nginx:path) specific
# uploading a lot of files at once requires less strictness.
[Definition]

_daemon = ${HERMES_MAIL_DAEMON}

_req_method = [A-Z]{3,}
_req_code = \d+
_req_uri = \S+{${HERMES_DRIVE_PATHS}}

failregex = ^<ADDR> -[^"]*\"%(_req_method)s\s+/(?:%(_req_uri)s)\b\S* HTTP/[^"]+" (?:%(_req_code)s)\s