# Fail2Ban configuration file
# matrix(nginx:path) specific
[Definition]

_daemon = mailu-front

_req_method = [A-Z]{3,}
_req_code = \d+
_req_uri = \S+{_matrix,_/_synapse/client|/_synapse/admin}
failregex = ^<ADDR> -[^"]*\"%(_req_method)s\s+/(?:%(_req_uri)s)\b\S* HTTP/[^"]+" (?:%(_req_code)s)\s