# Fail2Ban configuration file
# nginx:core specific
[Definition]

_daemon = mailu-front

_req_method = [A-Z]{3,}
_req_code = \d+
_req_uri = \S+
failregex = ^<ADDR> -[^"]*\"%(_req_method)s\s+/(?:%(_req_uri)s)\b\S* HTTP/[^"]+" (?:%(_req_code)s)\s

# ar(comment): this means I'm not distinguishing between types of request. 
# we can have different patience settings for different types of request:
# e.g. password attempts (tolerance:0), refreshing the page vs. DDoSing (short circuit:0 vs. excessive use:1), watching videos, etc.